name: himusic
description: "家庭共享硬盘音乐播放器"
publish_to: 'none'

version: 0.5.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dart_smb2: 0.1.2
  just_audio: ^0.10.6
  just_audio_media_kit: ^2.1.0
  media_kit_libs_windows_audio: ^1.0.9
  file_selector: ^1.1.0
  path: ^1.9.1
  just_waveform: 0.0.7
  path_provider: ^2.1.6
  metadata_audio: ^0.9.2
  charset_codec: ^0.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/artwork/
